name = "visualization-of-expense-data"
compatibility_date = "2026-06-06"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "expense-data-db"
database_id = "4010c137-5d25-4220-a2ea-17c11de1d1ae"
